spring:
  profiles:
    active: dev
  mvc:
    locale: zh_CN
    date-format: yyyy-MM-dd
  http:
    multipart:
      max-file-size: 10MB
  freemarker:
    allow-request-override: false
    cache: false
    check-template-location: false
    charset: UTF-8
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    suffix: .ftl
    request-context-attribute: request


#server
server:
  address: 127.0.0.1
  context-path: /live/
  port: 9090
  session-timeout: 30
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8
  error:
    path: /error


#logging
logging:
  level: warn
  file: ./logs/error.log

